# Site wide configuration

title                   : "Yury Kashnitsky"
description             : "Yury Kashnitsky's view on machine learning popular science, career development, programming. soft skills, etc."
author                  : yorko
logo                    : logo-120x120.png
teaser                  : teaser-blog.png
locale                  : en
url                     : https://yorko.github.io
feed:
  path                  : atom.xml
encoding                : UTF-8
google_analytics        : G-51NVNH4J5S
comments                : true

# Jekyll configuration

sass:
  sass_dir              : _sass
  style                 : compressed
permalink               : /:categories/:year/:title/
markdown                : kramdown
remote_theme            : jekyll/minima
highlighter             : rouge
kramdown:
  toc_levels            : 1..2
  mathjax               : true
  input                 : GFM
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-remote-theme

plugins:
 - jekyll-remote-theme
 - jekyll-feed


# Site owner
owner:
  name                  : "Yury Kashnitsky"
  web                   : https://yorko.github.io
  email                 : "yury.kashnitsky@gmail.com"
  twitter               : "ykashnitsky"
  github                : "Yorko"
  facebook              : "festline"
  bio                   : "Yury Kashnitsky is a Principal Machine Learning Scientist, NLP practitioner, Ph.D. in applied math, and leader of the open Machine Learning course mlcourse.ai"
  avatar                : bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname      : yorko-github-io

include: ["_pages", ".htaccess"]
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
